// <auto-generated />
using System;
using Eindopdracht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eindopdracht.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240110165807_RealDataSeed")]
    partial class RealDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbumSong", b =>
                {
                    b.Property<int>("AlbumsId")
                        .HasColumnType("int");

                    b.Property<int>("SongsId")
                        .HasColumnType("int");

                    b.HasKey("AlbumsId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("AlbumSong");
                });

            modelBuilder.Entity("Eindopdracht.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImage = "https://link-naar-coverfoto/queen-anato.jpg",
                            ReleaseYear = 1975,
                            Title = "A Night at the Opera"
                        },
                        new
                        {
                            Id = 2,
                            CoverImage = "https://link-naar-coverfoto/ed-sheeran-divide.jpg",
                            ReleaseYear = 2017,
                            Title = "÷ (Divide)"
                        },
                        new
                        {
                            Id = 3,
                            CoverImage = "https://link-naar-coverfoto/michael-jackson-thriller.jpg",
                            ReleaseYear = 1982,
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = 4,
                            CoverImage = "https://link-naar-coverfoto/john-lennon-imagine.jpg",
                            ReleaseYear = 1971,
                            Title = "Imagine"
                        },
                        new
                        {
                            Id = 5,
                            CoverImage = "https://link-naar-coverfoto/nirvana-nevermind.jpg",
                            ReleaseYear = 1991,
                            Title = "Nevermind"
                        },
                        new
                        {
                            Id = 6,
                            CoverImage = "https://link-naar-coverfoto/the-cure-three-imaginary-boys.jpg",
                            ReleaseYear = 1979,
                            Title = "Three Imaginary Boys"
                        },
                        new
                        {
                            Id = 7,
                            CoverImage = "https://link-naar-coverfoto/oasis-morning-glory.jpg",
                            ReleaseYear = 1995,
                            Title = "(What's the Story) Morning Glory?"
                        },
                        new
                        {
                            Id = 8,
                            CoverImage = "https://link-naar-coverfoto/leonard-cohen-various-positions.jpg",
                            ReleaseYear = 1984,
                            Title = "Various Positions"
                        },
                        new
                        {
                            Id = 9,
                            CoverImage = "https://link-naar-coverfoto/the-beatles-white-album.jpg",
                            ReleaseYear = 1968,
                            Title = "The Beatles (White Album)"
                        });
                });

            modelBuilder.Entity("Eindopdracht.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Queen",
                            DurationInSeconds = 354,
                            Genre = "Rock",
                            ReleaseDate = new DateTime(1975, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Ed Sheeran",
                            DurationInSeconds = 233,
                            Genre = "Pop",
                            ReleaseDate = new DateTime(2017, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Shape of You"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Michael Jackson",
                            DurationInSeconds = 294,
                            Genre = "Pop",
                            ReleaseDate = new DateTime(1983, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Billie Jean"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "John Lennon",
                            DurationInSeconds = 185,
                            Genre = "Soft rock",
                            ReleaseDate = new DateTime(1971, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Imagine"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Nirvana",
                            DurationInSeconds = 302,
                            Genre = "Grunge",
                            ReleaseDate = new DateTime(1991, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Smells Like Teen Spirit"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "The Cure",
                            DurationInSeconds = 174,
                            Genre = "Post-punk",
                            ReleaseDate = new DateTime(1979, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Boys Don't Cry"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Oasis",
                            DurationInSeconds = 258,
                            Genre = "Britpop",
                            ReleaseDate = new DateTime(1995, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wonderwall"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Leonard Cohen",
                            DurationInSeconds = 272,
                            Genre = "Folk",
                            ReleaseDate = new DateTime(1984, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hallelujah"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "The Beatles",
                            DurationInSeconds = 431,
                            Genre = "Pop",
                            ReleaseDate = new DateTime(1968, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hey Jude"
                        });
                });

            modelBuilder.Entity("AlbumSong", b =>
                {
                    b.HasOne("Eindopdracht.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eindopdracht.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
